init: create react app
wowarys/ad1202-final pull request #2
Opened 2024-10-16 15:25 UTC by aBacoding

2024-10-16 15:29 UTC, aBacoding reviewed
init: create react app

2024-10-17 08:11 UTC, wowarys requested changes

2024-10-17 08:11 UTC, wowarys commented on frontend/app/.gitignore
Добавь этот гитигнор который находится в корне проекта

2024-10-17 08:11 UTC, wowarys commented on frontend/app/package-lock.json
Точно лишнее, зачем нам `package-lock.json` в репе?

2024-10-17 08:11 UTC, wowarys commented on frontend/app/README.md
Тут readme не нужен, к тому же ничего полезного тут нет. Билдится все будет в докере, поэтому эта инструкция не нужна, я бы ее удалил полностью

2024-10-17 08:13 UTC, wowarys commented on frontend/app/package-lock.json
А, прогуглил, оказывается он нужен, тогда ок, дропаю коммент

2024-10-20 10:09 UTC, wowarys approved these changes

2024-10-20 10:10 UTC, merged